### ISSUE TITLE
Buttons zur Mitteilung fehlen bei Aufruf über E_Mail

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#112]
Wenn man dem Link aus einer E-Mail zur Mitteilung folgt, fehlen die Buttons oben rechts, insbesondere die Möglichkeit zur Bestätigung

**Comment by frostieDE** [comment]
Im Grunde fehlt nur die Bestätigung - alle anderen Buttons sind entweder rechts oder überflüssig (bspw. bei den Dateien, die sich ja unterhalb der Mitteilung befinden).
