### ISSUE TITLE
Volljährigkeit der SuS

### ISSUE THREAD

**Issue by frostieDE** [SchulIT/icc#114]
Aktuell wird die Volljährigkeit der SuS als Wahrheitswert ins System eingetragen. Da volljährige SuS auch Krankmeldungen absetzen können, ist ein regelmäßiger Import der SuS notwendig.

Wäre es nicht sinnvoller, das Geburtsdatum im ICC zu hinterlegen, sodass die Volljährigkeit tagesaktuell vorliegt? 

Als Gegenargument fällt mir spontan nur der Datenschutz ein.

/cc @M-Plu

**Comment by M-Plu** [comment]
Genau, darum haben wir damals überlegt, wie man einen automatisierten täglichen Import durchführen kann (Kommandozeile oder Ähnliches).

**Comment by frostieDE** [comment]
Okay. Dann kann das Issue hier gelöscht werden.
