### ISSUE TITLE
group-by Filter Vertretungsplan

### ISSUE THREAD

**Issue by H3R0M0** [SchulIT/icc#125]
Der Gruppieren-Filter wird Schülern angezeigt ändert jedoch nichts (auch nicht die Farbe).
Bei nicht-Schülern funktioniert der Filter wie gewollt.
Soll der Filter eventuell Schülern gar nicht angezeigt werden?

**Comment by frostieDE** [comment]
Vermutlich letzteres 🤷🏻‍♂️
