### ISSUE TITLE
Ressourcen Suchen: UND und ODER ermöglichen

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#130]
Es wäre gut, wenn der Benutzer bei der Filterung der Ressourcen festlegen könnte, ob er die Bedingungen mit UND oder ODER verknüpfen möchte.

**Comment by frostieDE** [comment]
Ist diese Funktion noch relevant?

**Comment by M-Plu** [comment]
Ich denke nicht, weil die Räume jetzt sehr ähnlich ausgestattet sind.
