### ISSUE TITLE
Unterrichtsbuch: Tage ausklappbar machen

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#156]
Die Stunden der einzelnen Unterrichtstage sollten ausklappbar sein und bei keinen fehlenden Einträgen bereits eingeklappt sein. Insbesondere auf kleinen Bildschirmen kommt man dann viel schneller zum aktuellen Tag.

**Comment by frostieDE** [comment]
Ist meiner Meinung nach nicht mehr relevant, da man Einträge am Schnellsten über die Startseite erledigt (auf kleinen Bildschirmen, auf denen man ja auch eigentlich gar kein ICC nutzen darf :-D).
