### ISSUE TITLE
Fehlerhafte Plattform bei "Verbundenen Apps"

### ISSUE THREAD

**Issue by Wiwaltill** [SchulIT/icc#161]
Die Plattform beim Terminplan ist fehlerhaft. Sollte nicht besser Terminplan-Synchronisation angezeigt werden?! Selbiges würde auf den Stundenplan zutreffen.

![Bildschirmfoto 2021-08-22 um 21 40 13](https://user-images.githubusercontent.com/74987472/130367943-5d8348da-a6ea-48bd-857e-55550ba82df1.png)

**Comment by frostieDE** [comment]
Für bestehende Stundenplan-Synchronsisationen wird es weiterhin falsch angezeigt.
