### ISSUE TITLE
Termine: Jahrgangsstufen fehlen zu Terminen im zweiten Halbjahr

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#165]
Der Terminplan zeigt keine Lerngruppen zu den Terminen im zweiten Halbjahr. Dadurch funktionieren auch keine Filterungen.

**Comment by frostieDE** [comment]
Liegt daran, dass es im zweiten Halbjahr noch keine Lerngruppen gibt (also auch keine Klassen-Lerngruppen)...

**Comment by M-Plu** [comment]
Das ist natürlich schlecht, weil dann zentrale Termine für die betroffenen nicht einsehbar sind. Könnte man nicht überlegen, bei fehlendem Abschnittsdaten auf den aktuellen Abschnitt zu zugreifen? Denn es gibt Termine wie Abitur oder Klassenfahrten, die man früh wissen muss.
