### ISSUE TITLE
Klausurplan: Schülerauswahl filtert nicht richtig

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#169]
Filtert man auf einen Schüler im Klausurplan, so wird zum einen der eigene Lehrername in der Filterung angezeigt. Zudem werden auch nicht alle Klausuren angezeigt, obwohl sie im Stufen-Klausurplan angezeigt werden (Beispiel siehe Teams-Chat).

**Comment by frostieDE** [comment]
Ich schätze mal, dass das Problem irgendwann in der Vergangenheit behoben wurde. Das Verhalten lässt sich jedenfalls nicht mehr reproduzieren.
