### ISSUE TITLE
Unterrichtsbuch: Liste Unentschluldigte Stunden nur bei Lehrern mit Entschuldungsrecht

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#181]
Aktuell werden unent. Stunden von Schülern in der Übersicht angezeigt, die man selbst nicht entschuldigt, also bspw. Sek-I Schüler in den Fachlehrerstunden.
Man müsste bei den SuS angeben, wer Stunden entschuldigen darf: Der Klassenlehrer/Tutor darf immer und dann müsste man definieren ob es auch die Fachlehrer dürfen.

**Comment by frostieDE** [comment]
Schon längst gelöst durch 503d3cb372562c41cd45611a10a9f50014eedae6

/duplicate #270
