### ISSUE TITLE
Fehlerhafte Anzeige von Entfällen

### ISSUE THREAD

**Issue by Wiwaltill** [SchulIT/icc#189]
Entfallene Stunden werden nur noch als "Plus als Vertreter" gekennzeichnet.

**Comment by frostieDE** [comment]
Bitte schreibe mir via Teams, um welche Vertretungen es sich handelt (GitHub ist als öffentliche Plattform dafür ungeeignet).

**Comment by Wiwaltill** [comment]
Da es sich nicht um eine bestimmte Vertretung handelt, dachte ich eher an einen generellen Fehler.

**Comment by frostieDE** [comment]
Es ist durchaus möglich, dass Vertretungen falsch klassifiziert werden. Daher frage ich ;-)
