### ISSUE TITLE
Doppelte Auflistung der Tutoren

### ISSUE THREAD

**Issue by Wiwaltill** [SchulIT/icc#197]
Seit der Veröffentlichung des Stundenplans zum 2. Halbjahr, werden in der Übersicht die Tutoren doppelt angezeigt. 

Beispiel: Lehrer A, Lehrer A, Lehrer B, Lehrer B

**Comment by frostieDE** [comment]
Genauer: Schüleransicht der Übersichtsseite, rechte Visitenkarte, gilt sowohl für Sek I als auch für Sek II

**Comment by Wiwaltill** [comment]
Fehler trotz Änderung nicht behoben. Was mir bis jetzt nicht aufgefallen war, ist, dass in der Lehrerliste ebenfalls die Klassen zu den Lehrer doppelt zugeordnet sind.
Somit könnte das Problem auch eventuell bei einer Dateneintragung passiert sein.
