### ISSUE TITLE
503 bei Filtern nach Lerngruppen im Klausurplan

### ISSUE THREAD

**Issue by H3R0M0** [SchulIT/icc#199]
Filtert man als Schüler im Klausurplan nach einer Lerngruppe, gibt das ICC einen Error 503 aus.

![image](https://user-images.githubusercontent.com/71940049/152567391-21125b19-f70e-40cd-9085-913c9a25cd7d.png)

**Comment by frostieDE** [comment]
Da wir den Hoster gewechselt haben, sollte das nicht mehr auftreten.
