### ISSUE TITLE
Abstände Icons (Dashboard)

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#225]
Das sieht etwas unschön aus:

![image](https://user-images.githubusercontent.com/48728275/183876927-545d7256-b0d3-445a-8f0d-a89547fcfa83.png)

**Comment by Wiwaltill** [comment]
Ebenfalls bei der Schüleransicht angebracht:

![Bildschirmfoto 2022-08-10 um 17 30 25](https://user-images.githubusercontent.com/74987472/183945398-c2ce84d6-2ef2-4a80-80c0-e8d01e05b605.png)
