### ISSUE TITLE
Neue Stundenplan-Ansicht

### ISSUE THREAD

**Issue by Wiwaltill** [SchulIT/icc#226]
- [x] Bei Schülern wird die Mitteilung zu den Neuerungen bei der Stundenplan Anzeige nicht angezeigt.
- [x] Für eine bessere Übersicht, wäre es besser nur eine KW anzuzeigen:

![Bildschirmfoto 2022-08-10 um 17 22 13](https://user-images.githubusercontent.com/74987472/183943060-59be2471-7367-4315-9efd-525fb8c588cb.png)

- [ ] Außerdem wird bei der letzten angezeigten KW zweimal der selbe Plan angezeigt:

![Bildschirmfoto 2022-08-10 um 17 25 30](https://user-images.githubusercontent.com/74987472/183943878-699272b9-cd09-4a7e-ac96-9112d33939fa.png)

**Comment by frostieDE** [comment]
Es gibt nun eine Einstellung, mit der man den Stundenplan auf die aktuelle Woche beschränken kann: 
![Uploading grafik.png…]()
