### ISSUE TITLE
Schülerstatus Dashboard

### ISSUE THREAD

**Issue by Wiwaltill** [SchulIT/icc#232]
"Aktive" in "Aktiv" umbenennen?!

![Bildschirmfoto 2022-08-13 um 12 32 58](https://user-images.githubusercontent.com/74987472/184479958-5e1885cc-de8d-49db-84e8-0e3105fe3ed2.png)

**Comment by frostieDE** [comment]
Diese Bezeichnung stammt aus der Schulverwaltungssoftware. Auf die Namensgebung haben wir keinen Einfluss.
