### ISSUE TITLE
Klassenleitung in der Oberstufe

### ISSUE THREAD

**Issue by Wiwaltill** [SchulIT/icc#233]
Kleines Detail für das Dashboard:
In der Oberstufe könnte man die Klassenleitung in "Stufenleitung" oder "Tutoren" umbenennen.

![Bildschirmfoto 2022-08-13 um 12 35 28](https://user-images.githubusercontent.com/74987472/184480003-aa061864-e793-4efc-8621-71c9d4ffafbd.png)

**Comment by frostieDE** [comment]
Das ICC kennt leider keine Oberstufe oder ähnliche Unterscheidungen wie Sek I bzw. Sek II. Eine Unterscheidung ist daher nicht möglich (oder nur mit Aufwand)
