### ISSUE TITLE
Hausaufgabenansicht im Unterrichts

### ISSUE THREAD

**Issue by frostieDE** [SchulIT/icc#238]
Für Lernzeiten ist eine Hausaufgaben-Ansicht hilfreich. Dann weiß man als Lehrkraft einer Lernzeit, welche Aufgaben die SuS erledigen müssen.

/cc @M-Plu

**Comment by M-Plu** [comment]
D. h. da wird die letzte Hausaufgabe jedes Faches angezeigt?

**Comment by frostieDE** [comment]
Der Einfachheit halber werden die Hausaufgaben der letzten sieben Tage angezeigt. Sowohl in der Klassenansicht des dUB als auch auf der Übersichtsseite der SuS/Eltern.
