### ISSUE TITLE
Neue Mitteilungen kennzeichnen

### ISSUE THREAD

**Issue by Wiwaltill** [SchulIT/icc#251]
Es wäre angenehm, wenn neue, ungelesene Mitteilungen hervorgehoben würden.

## Beispiel 1
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/74987472/187849283-0011e4af-8bf9-4bea-9538-5462ce1c3050.png">

## Beispiel 2
<img width="1433" alt="Bildschirmfoto 2022-09-01 um 08 50 11" src="https://user-images.githubusercontent.com/74987472/187850215-bb8c3400-f7c7-4fd4-bc0a-c5520c26de21.png">

**Comment by frostieDE** [comment]
Gelesene Mitteilungen kann man über das 3-Punkte-Menü ausblenden. Im Grunde ist das eine "gelesen"-Funktion, nur ohne Automatik ;-)
