### ISSUE TITLE
Dashboard: Tagestext oben anpinnen

### ISSUE THREAD

**Issue by Wiwaltill** [SchulIT/icc#260]
Je nach Schüler wäre es nett, die Tagestext oben anzeigen zu lassen.

<img width="1085" alt="Bildschirmfoto 2022-09-07 um 12 00 32" src="https://user-images.githubusercontent.com/74987472/188980654-e0eed833-abdc-492d-af73-abbdf58cc1ae.png">

Dies sollte über eine individuelle Einstellung möglich sein:

<img width="344" alt="Bildschirmfoto 2022-09-07 um 12 01 54" src="https://user-images.githubusercontent.com/74987472/188980660-8377ab22-caaa-4a5b-86a7-3829edd6f707.png">

**Comment by frostieDE** [comment]
Man könnte überlegen, die Tagestexte grundsätzlich oben oberhalb der Agenda anzuzeigen. @M-Plu

**Comment by M-Plu** [comment]
Von meiner Seite her ist das OK.

**Comment by frostieDE** [comment]
Gut, ich glaube bei den Untis-Ausdrucken war es auch immer oben und nicht unten :)
