### ISSUE TITLE
Dashboard: Warnende Mitteilung

### ISSUE THREAD

**Issue by Wiwaltill** [SchulIT/icc#263]
Die Warnmeldungen sollten direkt groß über der Übersicht angezeigt werden:

<img width="1433" alt="Bildschirmfoto 2022-09-07 um 12 31 49" src="https://user-images.githubusercontent.com/74987472/188981885-5dbf5e4c-c2c5-4c8a-a023-0dcfa7588826.png">

Eventuell noch ein Icon ergänzen:

<img width="1425" alt="Bildschirmfoto 2022-09-07 um 12 39 59" src="https://user-images.githubusercontent.com/74987472/188981909-0e03eb7c-925c-4822-b170-04b9841dd67c.png">

**Comment by frostieDE** [comment]
Der von dir gezeigte Bereich kann bereits jetzt mit Mitteilungen versehen werden - nämlich von Mitteilungen mit dem Ziel "Übersichtsseite" (es gibt auch die Ziele Stundenplan, Vertretungsplan etc.). Diese Mitteilungen sind dazu gedacht, über eventuelle Fehler auf der jeweiligen Seite aufzuklären.

Die von dir als "extrem wichtige Mitteilung" deklarierte Mitteilung ist grundsätzlich abhängig vom ausgewählten Datum, welches in der Leiste ausgewählt ist. Insofern muss diese Mitteilung (aus UX-Sicht) unterhalb dieser Leiste angezeigt werden.

**Comment by Wiwaltill** [comment]
Verständlich! Danke für die Erklärung. Demnach nicht mehr nötig.
