### ISSUE TITLE
Vorschlag: Icon Lehrerliste

### ISSUE THREAD

**Issue by Wiwaltill** [SchulIT/icc#264]
Das das Icon der Lehrerliste im Vergleich zu den anderen Icons eher unpassend:

![image](https://user-images.githubusercontent.com/74987472/188982741-0cb1ec04-27d2-4312-9166-938ad76c3f4d.png)

Eine Alternative wäre:

`fas fa-user-graduate`

<img width="654" alt="Bildschirmfoto 2022-09-07 um 12 36 23" src="https://user-images.githubusercontent.com/74987472/188982437-ae8e6cc4-810c-4b53-90cb-70c3bbbf5319.png">

`fas fa-user-tie`

<img width="673" alt="Bildschirmfoto 2022-09-07 um 12 36 36" src="https://user-images.githubusercontent.com/74987472/188982445-46c4e572-95e1-4748-ac0a-ab842c42486d.png">
(Obwohl dieses Icon eher für Schüler wäre.)

**Comment by frostieDE** [comment]
Ich glaube, an anderen Stellen haben wir für Lehrkräfte `fas fa-chalkboard-teacher` verwendet. Könnte man also auch im Menü so machen 👍🏻

**Comment by frostieDE** [comment]
Beim Bearbeiten merke ich: das Icon haben wir schon im Menü verwendet (sehen SuS nur nicht :-D)

![grafik](https://user-images.githubusercontent.com/3764924/189704344-92934d86-111c-48ae-ac39-eafe4d5a5574.png)

**Comment by Wiwaltill** [comment]
Blieben die zwei ersten Vorschläge:
`fas fa-user-graduate`
und
`fas fa-user-tie`.

**Comment by frostieDE** [comment]
Ich glaube, `fas fa-user-graduate` wird auch auf dem Dashboard verwendet. Das wäre dann etwas konsistent :)

![image](https://user-images.githubusercontent.com/3764924/190894700-dc0c063e-0cde-4ca7-b5b0-4b9772bbb03d.png)
