### ISSUE TITLE
Favicon und App-Icon

### ISSUE THREAD

**Issue by Wiwaltill** [SchulIT/icc#265]
Das ICC besitzt bis jetzt gar kein Favicon oder App-Icon. Das führ bei Verknüpfungen mit einem Home-Screen o.ä. zu einer eher unschönen Ansicht:

![IMG_CF2960264DDF-1](https://user-images.githubusercontent.com/74987472/189754066-af6f7bbf-fae1-4235-b88a-bfe01195598b.jpeg)

Hier könnte der Favicon Generator Abhilfe schaffen:
https://realfavicongenerator.net

Ein Beispiel für uns ist als ZIP angehängt.
[favicon_package_v0.16.zip](https://github.com/SchulIT/icc/files/9551703/favicon_package_v0.16.zip)

**Comment by Wiwaltill** [comment]
Da das Problem nicht nur das ICC betrifft, wäre das eigentlich auch eine Idee für das ServiceCenter, SSO etc.

**Comment by frostieDE** [comment]
Die Frage ist, ob man diese ganzen Icons tatsächlich im HTML-Quelltext hinterlegen muss, oder ob die Browser da einfach schauen, ob es eine Datei gibt...

Ich habe dein Pack mal hochgeladen (ohne HTML zu verändern)

**Comment by H3R0M0** [comment]
Also Chrome und Androidgeräte (als App-Icon) greifen sich die Dateien aus dem Verzeichnis.

Bei mir waren jedoch auch vor dem Hochladen Favicon und App-Icon vorhanden. (Die regulären drei Striche, statt wie jetzt das Logo).

**Comment by Wiwaltill** [comment]
Habe gerade nochmal nachgeschaut.

Tatsächlich werden jetzt bei mir in Safari als Favicon die 3 Streifen übergreifend erkannt.

![image](https://user-images.githubusercontent.com/74987472/193935535-fa37d864-b8f5-4785-8caf-b52becb67edf.png)

Außerdem scheint es tatsächlich zu reichen, die Apple Touch-Icons abzulegen, denn auch die werden jetzt erkannt.

![IMG_3016](https://user-images.githubusercontent.com/74987472/193935466-4d383e75-dbd6-4ca3-b793-2a341d8d4ee2.jpg)

So sieht schon viel besser aus!

**Comment by frostieDE** [comment]
Perfekt - weniger Arbeit für mich 😄
