### ISSUE TITLE
Dynamische Dokumente

### ISSUE THREAD

**Issue by Wiwaltill** [SchulIT/icc#269]
Bei Dokumenten wie dem Menüplan der Mensa wäre es angenehm, wenn dieser nicht als Mitteilung für jede KW eingestellt werden würde. Hier wäre eine Dynamische Dokumenten Ansicht praktisch.

**Comment by frostieDE** [comment]
Was genau meinst du mit "dynamische Dokumentenansicht"?

**Comment by Wiwaltill** [comment]
Ein Dokument, dass praktisch jede Woche ergänzt wird. Quasi eine Mitteilung, die auf einem anderen Bereich im Menü angezeigt wird.

Quasi so:

<img width="1718" alt="Bildschirmfoto 2022-09-22 um 19 18 53" src="https://user-images.githubusercontent.com/74987472/191811863-bbd2b39a-cce5-44d8-8fe2-c542e9818346.png">

Auf dem Dashboard könnte man das dann entweder in der Übersicht …

<img width="429" alt="Bildschirmfoto 2022-09-22 um 19 19 54" src="https://user-images.githubusercontent.com/74987472/191812014-26562095-f709-4d52-85fe-8a3eeaada4a7.png">

… oder als Spalte machen.

<img width="654" alt="Bildschirmfoto 2022-09-22 um 19 22 04" src="https://user-images.githubusercontent.com/74987472/191812122-44308fc9-f161-4fac-990a-57f97ecfc831.png">

Dann aber in Verknüpfung mit einer Einstellung zum Ausblenden.

<img width="419" alt="Bildschirmfoto 2022-09-22 um 19 22 48" src="https://user-images.githubusercontent.com/74987472/191812132-0c215319-a4da-4dfe-824d-96018d0e1b1d.png">

**Comment by frostieDE** [comment]
Im Grunde verschiebt man nur die Anzeige der Mitteilung. Solange der Essensplan nur als PDF vorliegt, halte ich den Kosten-/Nutzen-Aufwand für zu gering.
