### ISSUE TITLE
Schülergruppen/AGs

### ISSUE THREAD

**Issue by Wiwaltill** [SchulIT/icc#271]
Es wäre praktisch, wenn Mitteilungen und Dokumente an Gruppen zugeteilt werden könnten. Beispielsweise bei übergreifenden AGs wie zum Beispiel dem Orchester oder Gruppen wie der Schülervertretung.

**Comment by frostieDE** [comment]
Bei Mitteilungen geht das bereits über Lerngruppen, sofern diese in der Schulverwaltung hinterlegt sind. Bei Dokumenten ist das aber schwierig, weil Dokumente langlebig sind, Lerngruppen aber nicht. Die ändern sich jedes Halbjahr (bzw. werden jedes Halbjahr neu angelegt).
