### ISSUE TITLE
Feiertage auf dem Dashboard anzeigen

### ISSUE THREAD

**Issue by Wiwaltill** [SchulIT/icc#282]
Eine nützliche Funktion für das Dashboard wäre es, wie auch im Stundenplan bereits angezeigt, auch auf dem Dashboard die Feiertage als Unterrichtsfrei zu markieren. Gleiches gilt für Schulferien.

## Beispiel

Der Stundenplan zeigt den Feiertag am Dienstag:
![image](https://user-images.githubusercontent.com/74987472/199005021-a5c3b0cc-c7d3-490c-b14a-514d586789ab.png)

Das Dashboard zeigt dagegen den regulären Unterricht:
![image](https://user-images.githubusercontent.com/74987472/199005348-973e23f7-d629-4113-9951-7f2f2c48d6e3.png)

**Comment by frostieDE** [comment]
Das lag daran, dass der Termin "Allerheiligen" nicht für alle Klassen hinterlegt war @M-Plu Jetzt sollte es klappen
