### ISSUE TITLE
Unterrichtsbuch: Spalte für "hat teilgenommen"

### ISSUE THREAD

**Issue by frostieDE** [SchulIT/icc#287]
Die Sportler äußerten den Wunsch, eine Spalte "hat teilgenommen" bei der Anwesenheit zu notieren. So kann man in der Lernendenansicht schneller sehen, wann jemand nicht am Sportunterricht teilgenommen hat (obwohl die Person anwesend war).

**Comment by frostieDE** [comment]
@M-Plu Folgende Idee zur Umsetzung: es gibt die Möglichkeit (entweder zentral oder pro Unterricht?), beliebige Ja/Nein-Spalten zur Anwesenheit hinzuzufügen. Das System könnte man theoretisch auch nutzen, um Flags wie "ohne HA" oder "ohne Material" zu notieren

**Comment by M-Plu** [comment]
Mmh, ich weiß nicht. So freie Felder sind immer doof. Das muss man ja definieren und dokumentieren können, wofür die stehen. Eine Option für Sportunfähig ist OK.

**Comment by frostieDE** [comment]
Die Felder würde man anlegen. Ob man sie nutzt, bleibt dann jedem selbst überlassen - hätte den Charm, dass man dazu kein separates Programm benötigt :)

**Comment by M-Plu** [comment]
Dann sollte aber zentral die Bedeutung definiert und bei der Dokumentation auch ausgegeben werden.

**Comment by frostieDE** [comment]
> Dann sollte aber zentral die Bedeutung definiert und bei der Dokumentation auch ausgegeben werden.

Selbstverständlich :)
