### ISSUE TITLE
Ausdrucke Unterrichtsbücher korrigieren

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#300]
Folgende Punkte sind anzupassen:
- [x] Unicode Font einbinden
- [x] Für die Übersicht der Unterrichtsstunden und Fehlerzeiten Schriftgröße 8 verwenden.
- [ ] Graustufen verwenden

**Comment by frostieDE** [comment]
Kosten/Nutzen für das Anpassen des Farbschemas sind mir zu hoch, daher schließe ich das Issue hier (fürs erste).
