### ISSUE TITLE
Fehler bei der Anmeldung

### ISSUE THREAD

**Issue by LoPablo** [SchulIT/icc#314]
Hallo allerseits,

ich bin vor kurzem auf die Seite Schul-IT gestoßen und bin neugierig auf das ICC geworden. Um mir das mal genauer anzuschauen habe ich mir zu Testzwecken nun mal zwei virtuelle Maschinen geschnappt und den IDP sowie ICC auf Debian 12 aufgesetzt. Nach einigen Startschwierigkeiten mit node-sass und den SQL Migrations und einigen Translation-Dateien, welche laut Commit-message eigentlich automatisch generiert werden sollten, es aber nicht werden, habe ich nun zumindest eine lauffähige IDP Instanz.

ICC scheint auch an sich zu laufen. Es scheitert jedoch am Einloggen. Egal welchen Account ich verwende bekomme ich immer nur die Fehler-Meldung: "Fehler bei der Anmeldung Der Account ist nicht mit einem Lehrer verknüpft." oder in andern Varianten mit Schülerinnen und Schülern.

Ich finde in der bereitgestellten Dokumentation keine weiteren Infos, ob ich unabhängig von einer im IDP angelegten Lehrperson auch im ICC noch jemanden anlegen muss, damit ich mich überhaupt zum ersten mal ins ICC einloggen kann.

Würde mich sehr über eine Antwort freuen :)

**Comment by frostieDE** [comment]
Hallo,

erstmal spannend, dass du das Projekt gefunden hast. Herzlich Willkommen :) Tut mir leid, wenn der Start holprig war - das Setup ist schon ein paar Jahre alt und gerade im UI/Frontend-Bereich gibt es einiges zu tun (daran arbeite ich auch tatsächlich gerade).

Die Meldung erscheint bei Benutzern des Benutzertyps "Lehrkraft" oder "Schüler/Schülerin". Solche Accounts setzen beim ICC immer voraus, dass es eine entsprechende Lehrkraft bzw. Schüler/in im ICC gibt. 

Diese werden üblicherweise aus der Schulverwaltung importiert (da wir aus NRW kommen, geht das aktuell aus SchILD NRW und wird ab Sommer auch mit dem Nachfolger SchILD 3 funktionieren). Dummerweise funktioniert das bisherige Tool nur, wenn man bei SchILD 2 eine MSSQL-Datenbank verwendet (MySQL oder Access werden nicht unterstützt). Aber ab Sommer funktioniert das Schulverwaltungsprogramm des Landes ohnehin nur noch mit MySQL. 

Für den Start empfiehlt es sich, einen globalen Administrator anzulegen. Dieser Benutzer hat die Rolle `ROLE_SUPER_ADMIN` (vgl. https://icc.readthedocs.io/de/latest/admin/roles.html und https://icc.readthedocs.io/de/latest/admin/install.html#schritt-4-2-attribut-fur-rollen-erstellen). Damit kannst du dich dann erst einmal umsehen - wobei das System ohne Produktivdaten tatsächlich wenig sinn macht 😆 

Falls du etwas testen möchtest, dann kannst du folgendermaßen vorgehen:

1. Erstelle in der Datenverwaltung (Zahnräder oben rechts) einen Abschnitt für das aktuelle Schuljahr.
2. Setze diesen Abschnitt als Aktuellen Abschnitt in den Einstellungen (Zahnräder oben rechts)
3. Erstelle Lehrkräfte (direkt über die Datenverwaltung -> Lehrkräfte) und/oder Schüler (Datenverwaltung -> "EasyAdmin" -> Lernende). Wichtig ist: Lehrkräfte und SuS müssen mit Abschnitten verknüpft werden. Das geht auch über die Verwaltung in EasyAdmin (entweder unter Lehrkräfte oder Lernende)

Anschließend funktioniert auch das Anmelden mit einem Lehrkraft- oder SuS-Account. Voraussetzung ist jedoch, dass die hinterlegten E-Mail-Adressen (damit ist tatsächlich das Feld "E-Mail-Adresse" und nicht die Anmelde-E-Mail-Adresse gemeint) übereinstimmen.

Mein Wunsch ist es nach wie vor, Beispieldaten bereitzustellen (vielleicht sogar ein Demosystem). Aber dafür fehlt mir leider aktuell die Zeit (es ist auch gar nicht so einfach, Fake-Daten zu erstellen...).

Gruß
Marcel
