### ISSUE TITLE
Alle Termine ansehen.

### ISSUE THREAD

**Issue by Wiwaltill** [SchulIT/icc#318]
Wie damals beim alten ICC, wäre eine Option schön, im Terminplan alle Schultermine anzeigen lassen können. Beispielsweise Fahrten (wie z.B. die Skifahrt oder Abschlussfahrten).

**Comment by frostieDE** [comment]
Ich stelle mal die Frage nach der Relevanz :wink:

**Comment by frostieDE** [comment]
Macht ihr so etwas nicht mit euren SV-Lehrkräften? Die haben Zugriff auf den gesamten Kalender...

**Comment by Wiwaltill** [comment]
Wie es heute läuft, weiß ich nicht. Damals haben wir die Termine erstmal selbst datiert.
