### ISSUE TITLE
Kursbasierte Aufgabenansicht für Oberstufe

### ISSUE THREAD

**Issue by H3R0M0** [SchulIT/icc#323]
In der neuen Aufgabenübersicht auf dem Dashboard, werden Oberstufenschülern die eingetragenen Aufgaben der gesamten Stufe angezeigt. Dies ist nicht wirklich zielführend, da die Liste ewig lang ist und kaum ein Schüler die Nummer seiner GKs auswendig kennt. 
Daher sollte die Anzeige für die Oberstufe dahingehend überarbeitet werden, dass Schülern nur noch die Aufgaben der jeweiligen Kurse angezeigt werden, in denen sie sind.

**Comment by frostieDE** [comment]
Mimimi, direkt am Meckern :-P
