### ISSUE TITLE
Keine Auditierung beim Import

### ISSUE THREAD

**Issue by frostieDE** [SchulIT/icc#328]
Da das Audierieren beim Import die Datenbank des ICC für richtig viel Daten sorgt, ist eine Überlegung, diese während des Imports zu deaktivieren. Dann wird ausschließlich auditiert, wenn man Änderungen über die Web GUI vornimmt.

/cc @M-Plu

**Comment by M-Plu** [comment]
Ich denke, man sollte aber die Importe (Art) festhalten. Wenn man das noch mit einem Benutzer verknüpfen könnte, wäre das gut. Aber dafür müsste man zum Import ja Benutzer und Kennwort abfragen. Andererseits kann man so die Import authentifizieren.

**Comment by frostieDE** [comment]
Importe werden über ein Token authentifiziert, nicht über Benutzer. Insofern lässt sich nicht herausfinden, wer einen Import gestartet hat.
