### ISSUE TITLE
Benachrichtigung der Eltern bei Klassenbucheintrag

### ISSUE THREAD

**Issue by frostieDE** [SchulIT/icc#330]
Wird ein Kommentar im Unterrichtsbuch erstellt, so erhält bisher nur die Klassenleitung eine Benachrichtigung.

**Comment by M-Plu** [comment]
Das soll auch erstmal so bleiben gemäß Schulleitung. Hintergrund ist, das die Option zu Gesprächen vorab erhalten bleiben soll und die Klassenleitung den Text für die Benachrichtigung der Eltern anpassen können soll.
