### ISSUE TITLE
Dateiupload: Eine leere Zeile kann nicht entfernt werden

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#343]
Wenn man beim Upload einer Datei eine Datei (Zeile) hinzufügt und dann sofort wieder entfernen möchte, so geht das nicht. Der Klick auf den Mülleimer bleibt ohne Wirkung.

**Comment by frostieDE** [comment]
In welchem Dialog bist du?

**Comment by frostieDE** [comment]
Ah, in allen Dialogen :-D
