### ISSUE TITLE
Anzeigen von Elternmitteilungen bei Klassenleitungen

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#355]
Wenn eine Klassenleitung auf ihrem Dashboard den Haken zur Anzeige von Mitteilungen für ihre Klasse gesetzt hat, dann werden trotzdem keine Mitteilungen angezeigt, die an die Eltern der Klasse gerichtet sind.

**Comment by frostieDE** [comment]
Fun fact: grundsätzlich sehen Eltern keine Mitteilungen, die nur an die Kinder gehen. Sie sehen nur Mitteilungen für Eltern...

**Comment by M-Plu** [comment]
Klappt immer noch nicht.
