### ISSUE TITLE
Abwesenheitsmeldung: Fehlermeldung beim Hinzufügen eines E-Mail-Empfängers

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#359]
Will man unter Datenverwaltung > Abwesenheitsmeldung bei einer Abwesenheitsart einen zusätzlichen E-Mail-Empfänger hinzufügen, so kommt nach dem Klick auf Speichern diese Meldung.

![image](https://github.com/SchulIT/icc/assets/48728275/ac573883-e188-4e5c-881a-696b4ce69ef9)

**Comment by frostieDE** [comment]
Ah, scheinbar ein Problem mit der Datenbank. Die Spalte `details` darf laut Datenbank nicht `NULL` sein aber scheinbar ist sie leer...
