### ISSUE TITLE
Sortierung berücksicht Groß-/Kleinschreibung

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#39]
Die Raumliste bei der Buchung wird nicht sortiert.

**Comment by frostieDE** [comment]
Es ist so, dass die Sortierung von Zeichenketten aktuell die Groß- und Kleinschreibung beachtet. Großbuchstabe > Kleinbuchstabe. Die Funktion `strnatcasecmp` muss genutzt werden.
