### ISSUE TITLE
Liste der betroffenen Kursstunden durch Klausuren

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#40]
Es wäre gut, wenn es eine Liste pro Lehrer geben würde, in der man für alle eingepflegten Klausuren sieht, welche eigenen Unterrichtsstunden durch wie viele fehlende Schüler betroffen sind.

Die Ansicht ohne Kollegenfilter könnte dann auch die Schulverwaltung (Vertretungsplaner) nutzen.

**Comment by frostieDE** [comment]
Im Grunde ist das Problem "gelöst", indem man auf der eigenen Startseite in die Zukunft schaut. Eine separate Übersicht gibt es - mangels Relevanz? - nicht.
