### ISSUE TITLE
Tabellen sortierbar machen

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#41]
Es wäre gut, wenn man Tabellen nach Spalten als User sortieren könnten. Bspw. Übersicht
Unterricht einer Klasse nach Kurs, Größe usw.

**Comment by frostieDE** [comment]
Dieses Bibliothek sieht ganz brauchbar aus: https://github.com/fiduswriter/Simple-DataTables

**Comment by M-Plu** [comment]
Das Beispiel läuft schnell, die anderen Sachen musst du beurteilen.
