### ISSUE TITLE
Abwesenheitsmeldungen: Datums-Änderung durch Eltern einschränken.

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#428]
Eltern sollten bei der Erzeugung einer NEUEN Abwesenheitsmeldung wie folgt eingeschränkt werden:
Alle krankheitsbezogenen Meldungen (und Unvorhersehbares) sollten als Startdatum max. den Folgetag haben dürfen. Bei Beurlaubungen darf es natürlich auch später sein.

Bei vorhandenen krankheitsbedingten Meldungen sollten Eltern nur noch die Anhänge ändern und das Enddatum anpassen können. Sonst nichts. Bei genehmigten Beurlaubungen darf nichts mehr durch Eltern angepasst werden können.

**Comment by frostieDE** [comment]
> Alle krankheitsbezogenen Meldungen (und Unvorhersehbares) sollten als Startdatum max. den Folgetag haben dürfen. Bei Beurlaubungen darf es natürlich auch später sein.

Das ist sehr speziell und ggf. nicht immer erwünscht. Zum Beispiel wenn ich freitags mein Kind für Montag schon krankmelden möchte... 

> Bei vorhandenen krankheitsbedingten Meldungen sollten Eltern nur noch die Anhänge ändern und das Enddatum anpassen können. Sonst nichts. Bei genehmigten Beurlaubungen darf nichts mehr durch Eltern angepasst werden können.

Das ist jetzt umgesetzt.
