### ISSUE TITLE
Informationsblatt zu Klausuren für Aufsichten

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#462]
Es wäre schön, wenn man zu einer Klausur ein Informationsblatt ausgeben lassen könnte, welche folgende Informationen enthält.

- Kursbezeichnung 
- Kurslehrkraft
- Klausurdauer im Minuten (als Feld zum eintragen) 
- Klausurbeginn und Abgabe und für Mathe noch Abgabe hilfsmittelfreier Teil (als Felder zum Eintragen)
- erlaubte Hilfsmittel (als Feld zum eintragen
- Liste mit Klausurschreibern mit zusätzliche Spalten, wo evtl. Verlängerung (zum Beispiel NTA) und Bemerkungen eingetragen werden können.

**Comment by frostieDE** [comment]
Im Grunde lassen sich diese Informationen handschriftlich ergänzen, wenn man eine Detailansicht einer Klausur ausdruckt. Das war bisher immer mein "Hack".
