### ISSUE TITLE
Sortierung der Klassenarbeiten korrigieren

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#50]
Im Dialog zum Terminieren der Klassenarbeiten sollten nach Datum sortiert werden und evtl. nach KW gruppiert. Aktuell wird nach KW gruppiert und sortiert. Damit werden die Klausuren im Januar als erstes angezeigt.

**Comment by frostieDE** [comment]
Fix hat nichts gebracht

**Comment by frostieDE** [comment]
Der Fix bringt etwas, wenn man ihn auch einspielt :-)

**Comment by frostieDE** [comment]
Übrigens war die Sortierung der KW schon korrekt. KW3 wurde vor KW4x angezeigt, weil als Klausurdatum 13.01.2020 angegeben wurde :wink:
