### ISSUE TITLE
Erwähnungen im Vertretungsplan werden nicht erkannt

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#57]
Erwähnungen im Vertretungsplan werden nicht angezeigt. Evtl. falsche Syntax mit PLUE: statt nur PLUE ???

**Comment by frostieDE** [comment]
Update: sie werden aktuell falsch erkannt. Es reicht aus, wenn das Kürzel im Vertretungstext vorkommt. Das ist aber Quatsch, da das Kürzel teil eines Wortes sein kann.
