### ISSUE TITLE
Anzahl der DropDown-Einträge erhöhen

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#65]
Unter Listen Lerngruppen bitte die Anzahl der DropDown Einträge erhöhen. Denn der Suchbegriff E-GK3 wird dort nicht angezeigt (für die Q2).

Zudem wäre es gut, wenn man dort den Lehrer hinter der Gruppe mit einträgt.

**Comment by frostieDE** [comment]
Lerngruppen kennen aber keine Lehrkräfte :wink:

**Comment by M-Plu** [comment]
In der Realität schon, möglich mindestens eine.
