### ISSUE TITLE
Kollisionserkennung verbessern

### ISSUE THREAD

**Issue by frostieDE** [SchulIT/icc#86]
Aktuell gibt es noch viele Kollisionsmeldungen, obwohl gar keine Kollisionsmeldung vorliegt.

Im Folgenden werden alle Fälle gesammelt, bei denen eine Kollision gemeldet ist, obwohl es gar keine ist:

- [x] parallele Klausuraufsichten im gleichen Raum

**Comment by M-Plu** [comment]
Weitere Fälle, die (fälschlicherweise) Kollisionen erzeugen:

- [ ] Bereitschaften verlieren immer (wird immer durch andere Einträge überschrieben)
- [ ] Unterricht + Sondereinsatz + Entfall -> der Entfall sollte den passenden Stundenplaneintrag tilgen, der Sondereinsatz bleibt dann ohne Kollision übrig

**Comment by M-Plu** [comment]
- [ ] keine Kollision bei mehreren Einträgen im selben Raum

**Comment by frostieDE** [comment]
Inwiefern sind diese Kollisionen noch vorhanden?

**Comment by M-Plu** [comment]
Gute Frage. Mach hier mal zu. Wenn es dann wieder Kollisionen gibt, müssen wir direkt analysieren.
