### ISSUE TITLE
Ergebnisseite zur Krankmeldungen 

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#95]
Nach einer Krankmeldung sollte der "Melder" eine Seite mit dem Ergebnis der Krankmeldung erhalten, die er ausdrucken oder herunterladen kann, sodass er einen Nachweis hat.

**Comment by frostieDE** [comment]
Man sollte diese Mitteilung dann allerdings digital signieren (bspw. mit PGP). Nachteil: das Überprüfen der Signatur macht keinen Spaß, wenn die Nachricht analog vorliegt.

**Comment by frostieDE** [comment]
Zur Dokumentation: das Ganze wurde anderweitig in 1.2 gelöst. Der Melder, der Lernende, das vsl. Ende und der Zeitstempel werden auch in der Datenbank gespeichert für N Tage (einstellbar). Die Krankmeldungen können somit auch von Fachlehrkräften eingesehen werden.
