### ISSUE TITLE
Raumreservierungen mit Vertretungen zusammenführen

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/icc#98]
Wenn man einen Raum reserviert hat und dann der Vertretungsplan dies auch aufnimmt, sollten die Reservierung und Vertretung zusammengeführt werden. Dann gäbe es keine Dopplung wie im Anhang.
![Reservierung](https://user-images.githubusercontent.com/48728275/98847316-5eb78080-2450-11eb-8a38-55d8d8ebc6f4.PNG)

**Comment by frostieDE** [comment]
Idealerweise würde man die Reservierung löschen, weil sie durch den Vertretungsplan überschrieben wird.

**Comment by M-Plu** [comment]
Aber nur, wenn es meine eigene Reservierung ist und der Raum übereinstimmt.

**Comment by frostieDE** [comment]
Im Grunde hat man zwei Möglichkeiten:

1. Man Löscht die Reservierung beim Import des Vertretungsplans. Anstatt einer Kollisionsmail gibt es dann eine Mail, dass die Reservierung gelöscht wurde, da sie im Vertretungsplan abgebildet ist.
2. Man blendet die Reservierung einfach aus.

Im Grunde wäre natürlich Möglichkeit 1 besser, bei 2 gibt es den Vorteil, dass die Reservierung bleibt, wenn ein neuer Vertretungsplan hochgeladen wurde, der die Reservierung nciht mehr enthält.

**Comment by M-Plu** [comment]
Ich fände 1 sinnvoll.

**Comment by frostieDE** [comment]
Dann machen wir es aber auch ganz korrekt: Der Vertretungsplan löscht den Zeitbereich aus der Reservierung, der in der Vertretung angegeben wird. Beispiele: Reservierung 3.-5. Std.

* Fall 1: Vertretung 3.-5. Stunde in den Zielraum -> Reservierung löschen
* Fall 2: Vertretung 1.-6. Stunde in den Zielraum -> Reservierung löschen
* Fall 3: Vertretung 3./4. Stunde in den Zielraum -> Reservierung auf nur 5. Stunde ändern
* Fall 4: Vertretung 4. Stunde in den Zielraum -> Reservierung aufsplitten auf 3. Std und 5. Std. (es wird also eine weitere Reservierung angelegt)

Bei allen Aktionen werden jeweils E-Mails versendet.

**Comment by M-Plu** [comment]
Sehe ich genauso

**Comment by frostieDE** [comment]
Hm, also Fall 1 und 2 sind trivial und umgesetzt. Die anderen beiden Fälle kommen irgendwann in der Zukunft.

**Comment by frostieDE** [comment]
Issue wird aufgrund mangelnder Relevanz geschlossen.
